before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "bundle exec rake test_app"
bundler_args: --without development production --quiet
before_install:
  - echo "yes" | gem uninstall json
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres
script:
  - "export DISPLAY=:99.0"
  - "bundle exec rspec spec"
notifications:
  email:
    - ryan@spreecommerce.com
rvm:
  - 1.9.3
